language: ruby
branches:
  only:
  - pre-deploy
rvm:
  - 2.7
before_install:
  - gem install bundler
before_script:
  - chmod +x ./scripts/cibuild
script: ./scripts/cibuild

cache: bundler

deploy:
    provider: pages
    skip_cleanup: true
    token: $GITHUB_TOKEN
    local_dir: _site
    target_branch: master
    on:
        branch: pre-deploy
