language: ruby
branches:
  only:
  - pre-deploy
rvm:
  - 2.7
before_install:
  - gem install bundler
before_script:
  - chmod +x ./script/cibuild
script: ./script/cibuild

cache: bundler

exclude: [vendor]
sudo: false

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: _site
    target_branch: master
    on:
        branch: pre-deploy
