name: Seth Barberee
avatar: https://pbs.twimg.com/profile_images/901262532979064832/wCQqNS5j.jpg
title: Welcome to my homepage!
description: Random place on the internet for some random guy's stuff
permalink: pretty
footer-links:
    email: seth.barberee@gmail.com 
    github: SethBarberee
    twitter: s_barberee
    linkedin: seth-barberee-008023155
    youtube: channel/UCILpzRw7K9W9aAXp0teW5RA
    googleplus:

plugins_dir: ./_plugins
jekyll_get:
    - data: github
      json: 'https://api.github.com/users/SethBarberee/repos'
      cache: false

disqus:
    shortname: sethbarberee-github-io

paginate: true
#paginate:
#  collection:   posts
#  per_page:     10             # maximum number of items per page
#  limit:        5              # Maximum number of pages to paginate (false for unlimited)
#  permalink:    /page:num/     # pagination path (relative to template page)
#  title_suffix: " - page :num" # Append to template's page title
#  category:     ''             # Paginate items in this category
#  categories:   []             # Paginate items in any of these categories
#  tag:          ''             # Paginate items tagged with this tag
#  tags:         []             # Paginate items tagged with any of these tags
#  reversed:     false          # Reverse the order of the documents

kramdown:
    input: GFM
    syntax_highlighter: rouge
sass:
    style: :compressed
