name: Seth Barberee
avatar: https://pbs.twimg.com/profile_images/901262532979064832/wCQqNS5j.jpg
title: Welcome to my homepage!
description: Random place on the internet for some random guy's stuff
permalink: pretty
footer-links:
    email: seth.barberee@gmail.com 
    github: SethBarberee
    twitter: s_barberee
    linkedin:
    youtube: channel/UCILpzRw7K9W9aAXp0teW5RA
    googleplus:

kramdown:
    input: GFM
    syntax_highlighter: rouge
sass:
    style: :compressed
