name: Seth Barberee
title: Welcome to my homepage!
description: Random place on the internet for some random guy's stuff
permalink: pretty
footer-links:
    email: 
    github: SethBarberee
    twitter: s_barberee
    linkedin:
    youtube:
    googleplus:

kramdown:
    input: GFM
    syntax_highlighter: rouge
sass:
    style: :compressed
