name: Seth Barberee
avatar: https://pbs.twimg.com/profile_images/901262532979064832/wCQqNS5j.jpg
title: Welcome to my homepage!
description: Random place on the internet for some random guy's stuff
permalink: pretty
footer-links:
    email: seth.barberee@gmail.com 
    github: SethBarberee
    twitter: s_barberee
    linkedin: seth-barberee-008023155
    youtube: channel/UCILpzRw7K9W9aAXp0teW5RA
    googleplus:

plugins_dir: ./_plugins
jekyll_get:
    - data: github
      json: 'https://api.github.com/users/SethBarberee/repos'
      cache: false

plugins: 
    - jekyll-paginate-v2

collections:
    keyboards:
        output: true
        permalink: /keyboards/:path/
    anime:
        output: true
        permalink: /anime/:path/

permalink: /:year/:month/:title.html

# Pagination Settings
pagination:
  enabled: true
  per_page: 5
  permalink: '/page/:num/'
  title: ':title - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

autopages:
    enabled: true
    collections:
        layouts:
            - 'autopage_collection.html'
        title: 'Posts in collection :coll'
        permalink: '/collection/:coll'
        slugify:
            mode: 'default'
            case: false
    tags:
        layouts:
            - 'autopage_collections_tags.html'
        title: 'Posts tagged with :tag'
        permalink: '/tag/:tag'
        slugify:
            mode: 'default' # :tag is slugified
            case: false

kramdown:
    input: GFM
    syntax_highlighter: rouge
sass:
    style: :compressed
