name: Build Post

on: 
    push:
        branches: [ pre-deploy ]
    
jobs:
    workflow:
        name: Build the Blog Pages
        runs-on: ubuntu-latest

        steps:    
          - name: Checkout Repo
            uses: actions/checkout@v3

          - name: Setup Go
          - uses: actions/setup-go@v4
            with:
              go-version: '1.16.1' # The Go version to download (if necessary) and use.

          - name: Checkout openring
            run: cd .. && git clone https://git.sr.ht/~sircmpwn/openring # Clone to ROOT/openring

          - name: Build openring
            run: cd openring && go build

          - name: cd into website repo
            run: cd .. && cd sethbarberee.github.io

          - name: Setup Ruby
            uses: ruby/setup-ruby@v1
            with:
                ruby-version: 2.7

          - name: Generate openring posts
            run: ../openring/openring \
                  -s https://www.supergoodcode.com/feed.xml \
                  -s https://emersion.fr/blog/atom.xml \
                  -s https://drewdevault.com/blog/index.xml \
                  < in.html \
                  > _includes/openring.html

          - name: Build tags
            run: python _plugins/compile_tags.py 

          - name: 🔨 install dependencies & build site
            uses: limjh16/jekyll-action-ts@v2
            with:
              enable_cache: true

          - name: 🚀 deploy
            uses: peaceiris/actions-gh-pages@v3
            with:
              github_token: ${{ secrets.GITHUB_TOKEN }}
              publish_dir: ./_site
